import type { Metadata } from "next";
import { Inter, Instrument_Serif, JetBrains_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

// Trimmed font weights: every extra weight = one extra woff2 over the
// wire (~30-50 KB each). 400/600/700 covers body, semibold, and bold
// CTAs; heavier weights gracefully degrade via font-display: swap.
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["500"],
  display: "swap",
});

const SITE_URL = process.env.NEXT_PUBLIC_APP_URL || "https://zaptext.shop";
const SITE_NAME = "ZapText";
const DESCRIPTION =
  "WhatsApp AI that books, collects, and closes — not just answers. Built for Indian SMBs: restaurants, salons, gyms, coaching, real estate, e-commerce, tiffin & grocery. Multi-bot, multi-branch, vertical compliance (FSSAI / RERA / DPDPA), Hindi + regional languages, voice-note ready. Try free for 100 replies.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — AI WhatsApp Bots for Indian Businesses`,
    template: `%s · ${SITE_NAME}`,
  },
  description: DESCRIPTION,
  applicationName: SITE_NAME,
  generator: "Next.js",
  keywords: [
    "WhatsApp bot India",
    "WhatsApp AI bot India",
    "WhatsApp chatbot India",
    "WhatsApp business AI alternative",
    "WhatsApp business booking bot",
    "Hindi WhatsApp bot",
    "Hinglish chatbot",
    "WhatsApp Business API",
    "SMB automation India",
    "restaurant WhatsApp bot",
    "tiffin WhatsApp bot",
    "salon booking bot",
    "gym membership bot",
    "coaching institute chatbot",
    "real estate WhatsApp bot RERA",
    "ecommerce WhatsApp bot",
    "grocery WhatsApp bot",
    "ZapText",
  ],
  authors: [{ name: "ZapText" }],
  creator: "ZapText",
  publisher: "ZapText",
  category: "Business",
  referrer: "origin-when-cross-origin",
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: SITE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} — AI WhatsApp Bots for Indian Businesses`,
    description: DESCRIPTION,
    // OG image is auto-generated by `app/opengraph-image.tsx` (Next.js
    // file-based metadata). Don't list it explicitly here.
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} — AI WhatsApp Bots for Indian SMBs`,
    description: DESCRIPTION,
    // Twitter card image is auto-generated by `app/twitter-image.tsx`.
  },
  // Favicon + apple-touch-icon are generated at the edge via
  // `app/icon.tsx` and `app/apple-icon.tsx`. The previous override
  // pointed both at `/logo.png` (2000x2000, 649 KB) which forced every
  // visitor to download ~650 KB just for a 32x32 tab icon.
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${inter.variable} ${instrumentSerif.variable} ${jetbrainsMono.variable} h-full antialiased`}
        suppressHydrationWarning
      >
        <body className="min-h-full flex flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange
          >
            <main className="flex-1">
              {children}
            </main>
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
