// ─── Plan Definitions (client-safe, no server-only imports) ───

export const PLANS = {
  starter: {
    name: 'Starter',
    price: 2999,
    setupFee: 0,
    originalSetupFee: 4999,
    bots: 1,
    numbers: 1,
    conversations: 500,
    messages: 500,
    extraBotPrice: null as number | null,
    features: [
      '1 WhatsApp Bot',
      '1 WhatsApp number',
      'Up to 500 conversations/month',
      'FAQ handling + auto-reply',
      'Monthly summary report',
      'Email support',
    ],
  },
  growth: {
    name: 'Growth',
    price: 5999,
    setupFee: 0,
    originalSetupFee: 7999,
    bots: 3,
    numbers: 3,
    conversations: -1, // unlimited
    messages: -1,
    extraBotPrice: 1499,
    highlighted: true,
    features: [
      'Up to 3 WhatsApp Bots',
      '3 WhatsApp numbers (locations/departments)',
      'Unlimited conversations',
      'Booking & scheduling system',
      'Client dashboard with analytics',
      'Availability calendar management',
      'Automated reminders + notifications',
      'Daily summary reports',
      'WhatsApp + Email support',
      'Extra bot: ₹1,499/mo',
    ],
  },
  pro: {
    name: 'Pro',
    price: 9999,
    setupFee: 0,
    originalSetupFee: 14999,
    bots: 5,
    numbers: 5,
    conversations: -1,
    messages: -1,
    extraBotPrice: 1299,
    features: [
      'Up to 5 WhatsApp Bots',
      '5 WhatsApp numbers',
      'Everything in Growth',
      'Lead scoring',
      'Escalation alerts',
      'Conversation export',
      'Custom bot personality per number',
      'Monthly strategy call',
      'Priority support (4hr response)',
      'Extra bot: ₹1,299/mo',
    ],
  },
  enterprise: {
    name: 'Enterprise',
    price: 19999,
    setupFee: 0,
    originalSetupFee: 24999,
    bots: 10,
    numbers: 10,
    conversations: -1,
    messages: -1,
    extraBotPrice: 999,
    features: [
      'Up to 10 WhatsApp Bots',
      '10 WhatsApp numbers',
      'Everything in Pro',
      'Dedicated account manager',
      'Custom integrations',
      'API access',
      'White-label option',
      'Weekly optimization calls',
      '99.9% uptime SLA',
      'Extra bot: ₹999/mo',
    ],
  },
} as const;

export type PlanKey = keyof typeof PLANS;
